var mc_drops = [
	{
		boss:"鲁西弗隆",
		num_drops: 3, 
		items:[
			{name: '<div><a class="q4" href="">力量护手</a></div>', drop_rate:38},
			{name: '<div><a class="q4" href="">恶魔之心手套</a></div>', drop_rate:38},
			{name: '<div><a class="q4" href="">启示项链</a></div>', drop_rate:29},
			{name: '<div><a class="q4" href="">塞纳里奥长靴</a></div>', drop_rate:28},
			{name: '<div><a class="q4" href="">奥术师便鞋</a></div>', drop_rate:28},
			{name: '<div><a class="q4" href="">秩序之源战靴/大力之怒长靴</a></div>', drop_rate:15},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">沉重的黑铁戒指</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">法力风暴护腿</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">法术能量之戒</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">波动长袍</a></div>', drop_rate:4}
	]},
	{
		boss:"玛格曼达",
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">震地者</a></div>', drop_rate:36},
			{name: '<div><a class="q4" href="">速射强弓</a></div>', drop_rate:34},
			{name: '<div><a class="q4" href="">预言短裤</a></div>', drop_rate:34},
			{name: '<div><a class="q4" href="">塞纳里奥护腿</a></div>', drop_rate:33},
			{name: '<div><a class="q4" href="">恶魔之心短裤</a></div>', drop_rate:33},
			{name: '<div><a class="q4" href="">稳固之力勋章</a></div>', drop_rate:33},
			{name: '<div><a class="q4" href="">奥术师护腿</a></div>', drop_rate:32},
			{name: '<div><a class="q4" href="">力量腿铠</a></div>', drop_rate:31},
			{name: '<div><a class="q4" href="">夜幕杀手短裤</a></div>', drop_rate:31},
			{name: '<div><a class="q4" href="">巨人追猎者护腿</a></div>', drop_rate:30},
			{name: '<div><a class="q4" href="">艾斯卡达尔的右爪</a></div>', drop_rate:30},
			{name: '<div><a class="q4" href="">秩序之源腿铠/大地之怒腿甲</a></div>', drop_rate:18},
			{name: '<div><a class="q4" href="">火焰符文魔典</a></div>', drop_rate:12},
			{name: '<div><a class="q4" href="">迅击戒指</a></div>', drop_rate:12},
			{name: '<div><a class="q4" href="">黑曜石之刃</a></div>', drop_rate:12},
			{name: '<div><a class="q4" href="">古代熔火皮手套</a></div>', drop_rate:11},
			{name: '<div><a class="q4" href="">烈焰守卫护手</a></div>', drop_rate:11},
			{name: '<div><a class="q4" href="">燃魔腰带</a></div>', drop_rate:11},
			{name: '<div><a class="q4" href="">短暂能量护符</a></div>', drop_rate:11},
			{name: '<div><a class="q4" href="">岩浆长靴</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:6},
			{name: '<div><a class="q4" href="">地核护肩</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">烈焰行者重靴</a></div>', drop_rate:5}
	]},
	{
		boss:"基赫纳斯", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">预言手套</a></div>', drop_rate:41},
			{name: '<div><a class="q4" href="">夜幕杀手手套</a></div>', drop_rate:40},
			{name: '<div><a class="q4" href="">力量马靴</a></div>', drop_rate:31},
			{name: '<div><a class="q4" href="">巨人追猎者长靴</a></div>', drop_rate:31},
			{name: '<div><a class="q4" href="">秩序之源护手/大地之怒护手</a></div>', drop_rate:22},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">巫术匕首</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">沉重的黑铁戒指</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">法力风暴护腿</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">法术能量之戒</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">波动长袍</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">火蜥蜴鳞片短裤</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">稳固护腕</a></div>', drop_rate:7},
			{name: '<div><a class="q4" href="">赤红震荡者</a></div>', drop_rate:7}
	]},
	{
		boss:"加尔", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">光环石锤</a></div>', drop_rate:27},
			{name: '<div><a class="q4" href="">残忍利刃</a></div>', drop_rate:26},
			{name: '<div><a class="q4" href="">血腥撕裂者</a></div>', drop_rate:26},
			{name: '<div><a class="q4" href="">钻孔虫之碟</a></div>', drop_rate:26},
			{name: '<div><a class="q4" href="">塞纳里奥头盔</a></div>', drop_rate:25},
			{name: '<div><a class="q4" href="">夜幕杀手头巾</a></div>', drop_rate:25},
			{name: '<div><a class="q4" href="">奥术师头冠</a></div>', drop_rate:25},
			{name: '<div><a class="q4" href="">巨人追猎者头盔</a></div>', drop_rate:25},
			{name: '<div><a class="q4" href="">力量头盔</a></div>', drop_rate:24},
			{name: '<div><a class="q4" href="">恶魔之心角饰</a></div>', drop_rate:24},
			{name: '<div><a class="q4" href="">预言头饰</a></div>', drop_rate:24},
			{name: '<div><a class="q4" href="">秩序之源头盔/大地之怒头盔</a></div>', drop_rate:14},
			{name: '<div><a class="q4" href="">古代熔火皮手套</a></div>', drop_rate:9},
			{name: '<div><a class="q4" href="">火焰符文魔典</a></div>', drop_rate:9},
			{name: '<div><a class="q4" href="">燃魔腰带</a></div>', drop_rate:9},
			{name: '<div><a class="q4" href="">短暂能量护符</a></div>', drop_rate:9},
			{name: '<div><a class="q4" href="">迅击戒指</a></div>', drop_rate:9},
			{name: '<div><a class="q4" href="">黑曜石之刃</a></div>', drop_rate:9},
			{name: '<div><a class="q4" href="">烈焰守卫护手</a></div>', drop_rate:8},
			{name: '<div><a class="q4" href="">逐风者禁锢之颅</a></div>', drop_rate:6},
			{name: '<div><a class="q4" href="">地核护肩</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">岩浆长靴</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:4}
	]},
	{
		boss:"迦顿男爵", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">奥术师衬肩</a></div>', drop_rate:45},
			{name: '<div><a class="q4" href="">魔法导师的封印</a></div>', drop_rate:44},
			{name: '<div><a class="q4" href="">塞纳里奥肩甲</a></div>', drop_rate:43},
			{name: '<div><a class="q4" href="">恶魔之心护肩</a></div>', drop_rate:43},
			{name: '<div><a class="q4" href="">秩序之源肩铠/大地之怒肩饰</a></div>', drop_rate:23},
			{name: '<div><a class="q4" href="">古代熔火皮手套</a></div>', drop_rate:6},
			{name: '<div><a class="q4" href="">火焰符文魔典</a></div>', drop_rate:6},
			{name: '<div><a class="q4" href=""><div><a class="q5" href="https://cn.classic.wowhead.com/item=18563">逐风者禁锢之颅</a></div>', drop_rate:6},
			{name: '<div><a class="q4" href="">燃魔腰带</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">短暂能量护符</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">迅击戒指</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">黑曜石之刃</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">烈焰守卫护手</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:3},
			{name: '<div><a class="q4" href="">岩浆长靴</a></div>', drop_rate:3}
	]},
	{
		boss:"沙斯拉尔", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">塞纳里奥手套</a></div>', drop_rate:42},
			{name: '<div><a class="q4" href="">奥术师手套</a></div>', drop_rate:42},
			{name: '<div><a class="q4" href="">巨人追猎者手套</a></div>', drop_rate:41},
			{name: '<div><a class="q4" href="">恶魔之心便鞋</a></div>', drop_rate:33},
			{name: '<div><a class="q4" href="">预言之靴</a></div>', drop_rate:33},
			{name: '<div><a class="q4" href="">夜幕杀手长靴</a></div>', drop_rate:32},
			{name: '<div><a class="q4" href="">巫术匕首</a></div>', drop_rate:27},
			{name: '<div><a class="q4" href="">法术能量之戒</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">波动长袍</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">赤红震荡者</a></div>', drop_rate:4}
	]},
	{
		boss:"萨弗隆先驱者", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">暗影之击</a></div>', drop_rate:46},
			{name: '<div><a class="q4" href="">力量肩铠</a></div>', drop_rate:44},
			{name: '<div><a class="q4" href="">夜幕杀手护肩</a></div>', drop_rate:44},
			{name: '<div><a class="q4" href="">预言衬肩</a></div>', drop_rate:44},
			{name: '<div><a class="q4" href="">巨人追猎者肩饰</a></div>', drop_rate:43},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">巫术匕首</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">沉重的黑铁戒指</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">法力风暴护腿</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">法术能量之戒</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">火蜥蜴鳞片短裤</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">稳固护腕</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">赤红震荡者</a></div>', drop_rate:5}
	]},
	{
		boss:"焚化者古雷曼格", 
		num_drops: 4,
		items:[
			{name: '<div><a class="q4" href="">碧空之歌</a></div>', drop_rate:37},
			{name: '<div><a class="q4" href="">奥术师长袍</a></div>', drop_rate:36},
			{name: '<div><a class="q4" href="">统御法杖</a></div>', drop_rate:36},
			{name: '<div><a class="q4" href="">夜幕杀手胸甲</a></div>', drop_rate:35},
			{name: '<div><a class="q4" href="">巨人追猎者胸甲</a></div>', drop_rate:35},
			{name: '<div><a class="q4" href="">预言法袍</a></div>', drop_rate:35},
			{name: '<div><a class="q4" href="">恶魔之心长袍</a></div>', drop_rate:34},
			{name: '<div><a class="q4" href="">爆击猎枪</a></div>', drop_rate:34},
			{name: '<div><a class="q4" href="">力量胸甲</a></div>', drop_rate:33},
			{name: '<div><a class="q4" href="">塞纳里奥胸甲</a></div>', drop_rate:32},
			{name: '<div><a class="q4" href="">秩序之源胸甲/大地之怒外衣</a></div>', drop_rate:20},
			{name: '<div><a class="q4" href="">古代熔火皮手套</a></div>', drop_rate:5},
			{name: '<div><a class="q4" href="">火焰符文魔典</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">烈焰守卫护手</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">燃魔腰带</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">短暂能量护符</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">迅击戒指</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">黑曜石之刃</a></div>', drop_rate:4},
			{name: '<div><a class="q4" href="">召火腿甲</a></div>', drop_rate:3}
	]},
	{
		boss:"火焰之王的宝箱", 
		num_drops:3,
		items:[
			{name: '<div><a class="q4" href="">远古石叶</a></div>', drop_rate:49},
			{name: '<div><a class="q4" href="">神圣之眼</a></div>', drop_rate:49},
			{name: '<div><a class="q4" href="">眠火手套</a></div>', drop_rate:26},
			{name: '<div><a class="q4" href="">狂野肩铠</a></div>', drop_rate:22},
			{name: '<div><a class="q4" href="">防火披风</a></div>', drop_rate:21},
			{name: '<div><a class="q4" href="">灼烧指环</a></div>', drop_rate:20},
			{name: '<div><a class="q4" href="">熔火胫甲</a></div>', drop_rate:20},
			{name: '<div><a class="q4" href="https://cn.classic.wowhead.com/item=18805">熔火犬牙</a></div>', drop_rate:18},
			{name: '<div><a class="q4" href="">耳语秘言腰带</a></div>', drop_rate:18},
			{name: '<div><a class="q4" href="">芬克的熔岩挖掘器</a></div>', drop_rate:17},
			{name: '<div><a class="q4" href="">真龙护腕</a></div>', drop_rate:16},
			{name: '<div><a class="q4" href="">火焰卫士护肩</a></div>', drop_rate:14}
	]},
	{
		boss:"拉格纳罗斯", 
		num_drops: 4,
		items:[
			{name: '<div><a class="q4" href="">纯焰精华</a></div>', drop_rate:43},
			{name: '<div><a class="q4" href="">灵风短裤</a></div>', drop_rate:37},
			{name: '<div><a class="q4" href="">怒风腿甲</a></div>', drop_rate:35},
			{name: '<div><a class="q4" href="">毁灭之刃</a></div>', drop_rate:31},
			{name: '<div><a class="q4" href="">复仇护腿</a></div>', drop_rate:29},
			{name: '<div><a class="q4" href="">愤怒腿铠</a></div>', drop_rate:29},
			{name: '<div><a class="q4" href="">萨弗拉斯指环</a></div>', drop_rate:29},
			{name: '<div><a class="q4" href="">卓越护腿</a></div>', drop_rate:27},
			{name: '<div><a class="q4" href="">环雾披风</a></div>', drop_rate:27},
			{name: '<div><a class="q4" href="">龙血斗篷</a></div>', drop_rate:27},
			{name: '<div><a class="q4" href="">冲击束带</a></div>', drop_rate:25},
			{name: '<div><a class="q4" href="">埃古雷亚指环</a></div>', drop_rate:22},
			{name: '<div><a class="q4" href="">玛利斯达尔防御者</a></div>', drop_rate:22},
			{name: '<div><a class="q4" href="">血牙短裤</a></div>', drop_rate:22},
			{name: '<div><a class="q4" href="">审判腿铠/无尽风暴护腿</a></div>', drop_rate:20},
			{name: '<div><a class="q4" href="">巨龙追猎者腿甲</a></div>', drop_rate:20},
			{name: '<div><a class="q4" href="">毁灭王冠</a></div>', drop_rate:20},
			{name: '<div><a class="q4" href="">火焰之王的项圈</a></div>', drop_rate:18},
			{name: '<div><a class="q5" href="">萨弗拉斯之眼</a></div>', drop_rate:12},
			{name: '<div><a class="q4" href="">削骨之刃</a></div>', drop_rate:8},
			{name: '<div><a class="q4" href="">烈焰碎片</a></div>', drop_rate:8},
			{name: '<div><a class="q4" href="">脊骨收割者</a></div>', drop_rate:4}
	]}
]