var bwl_drops = [
	{
		boss:"狂野的拉格佐尔",
		num_drops: 3, 
		items:[
			{name: '<div><a class="q4" href="">卓越束腕</a></div>'},
			{name: '<div><a class="q4" href="">愤怒护腕</a></div>'},
			{name: '<div><a class="q4" href="">巨龙追猎者护腕</a></div>'},
			{name: '<div><a class="q4" href="">灵风束腕</a></div>'},
			{name: '<div><a class="q4" href="">血牙护腕</a></div>'},
			{name: '<div><a class="q4" href="">黑龙之书</a></div>'},
			{name: '<div><a class="q4" href="">奥术能量宝石</a></div>'},
			{name: '<div><a class="q4" href="">疾速进化手套</a></div>'},
			{name: '<div><a class="q4" href="">复仇护腕</a></div>'},
			{name: '<div><a class="q4" href="">怒风护腕</a></div>'},
            {name: '<div><a class="q4" href="">审判束腕/无尽风暴护腕</a></div>'},
			{name: '<div><a class="q4" href="">狂野之刃</a></div>'},
			{name: '<div><a class="q4" href="">碎脊者</a></div>'},
			{name: '<div><a class="q4" href="">黑翼衬肩</a></div>'}
	]},
	{
		boss:"堕落的瓦拉斯塔兹",
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">灵风腰带</a></div>'},
			{name: '<div><a class="q4" href="">血牙腰带</a></div>'},
			{name: '<div><a class="q4" href="">愤怒腰带</a></div>'},
			{name: '<div><a class="q4" href="">卓越腰带</a></div>'},
			{name: '<div><a class="q4" href="">复仇腰带</a></div>'},
			{name: '<div><a class="q4" href="">怒风腰带</a></div>'},
			{name: '<div><a class="q4" href="">龙魂坠饰</a></div>'},
			{name: '<div><a class="q4" href="">巨龙追猎者腰带</a></div>'},
			{name: '<div><a class="q4" href="">变形符文</a></div>'},
			{name: '<div><a class="q4" href="">思维加速宝石</a></div>'},
			{name: '<div><a class="q4" href="">无尽怒气头盔</a></div>'},
			{name: '<div><a class="q4" href="">龙牙之刃</a></div>'},
			{name: '<div><a class="q4" href="">审判腰带/无尽风暴腰带</a></div>'},
			{name: '<div><a class="q4" href="">红龙防护者</a></div>'}
	]},
	{
		boss:"勒什雷尔", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">愤怒马靴</a></div>'},
			{name: '<div><a class="q4" href="">灵风长靴</a></div>'},
			{name: '<div><a class="q4" href="">卓越长靴</a></div>'},
			{name: '<div><a class="q4" href="">复仇战靴</a></div>'},
			{name: '<div><a class="q4" href="">巨龙追猎者胫甲</a></div>'},
			{name: '<div><a class="q4" href="">血牙长靴</a></div>'},
			{name: '<div><a class="q4" href="">黑龙肩铠</a></div>'},
			{name: '<div><a class="q4" href="">怒风长靴</a></div>'},
			{name: '<div><a class="q4" href="">毒性图腾</a></div>'},
			{name: '<div><a class="q4" href="">生命宝石</a></div>'},
			{name: '<div><a class="q4" href="">奥术精准护腕</a></div>'},
			{name: '<div><a class="q4" href="">审判马靴/无尽风暴胫甲</a></div>'},
			{name: '<div><a class="q4" href="">击心者</a></div>'},
            {name: '<div><a class="q4" href="">玛拉达斯，黑龙军团的符文之剑</a></div>'}
	]},
	{
		boss:"费尔默", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">黑灰长袍</a></div>'},
			{name: '<div><a class="q4" href="">黑龙之爪</a></div>'},
			{name: '<div><a class="q4" href="">火喉之握</a></div>'},
			{name: '<div><a class="q4" href="">火喉披风</a></div>'},
			{name: '<div><a class="q4" href="">盲目光芒卷轴</a></div>'},
			{name: '<div><a class="q4" href="">卓越护手</a></div>'},
			{name: '<div><a class="q4" href="">堕落十字军腿甲</a></div>'},
			{name: '<div><a class="q4" href="">愤怒护手</a></div>'},
			{name: '<div><a class="q4" href="">灵风手套</a></div>'},
			{name: '<div><a class="q4" href="">紧绷的龙皮腰带</a></div>'},
			{name: '<div><a class="q4" href="">龙爪肩铠</a></div>'},
			{name: '<div><a class="q4" href="">审判护手/无尽风暴护手</a></div>'},
			{name: '<div><a class="q4" href="">复仇手套</a></div>'},
			{name: '<div><a class="q4" href="">巨龙追猎者护手</a></div>'},
			{name: '<div><a class="q4" href="">自然之盟水晶</a></div>'},
			{name: '<div><a class="q4" href="">黑石之戒</a></div>'},
			{name: '<div><a class="q4" href="">血牙手套</a></div>'},
			{name: '<div><a class="q4" href="">首领锁链腿甲</a></div>'},
			{name: '<div><a class="q4" href="">怒风护手</a></div>'},
			{name: '<div><a class="q4" href="">恢复宝石</a></div>'},
			{name: '<div><a class="q4" href="">暗影之翼</a></div>'},
			{name: '<div><a class="q4" href="">龙爪巨斧</a></div>'}
	]},
	{
		boss:"埃博诺克", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">庇护者</a></div>', drop_rate: 42},
			{name: '<div><a class="q4" href="">专注指环</a></div>', drop_rate: 33},
			{name: '<div><a class="q4" href="">龙牙饰物</a></div>', drop_rate: 33},
			{name: '<div><a class="q4" href="">黑焰手套</a></div>', drop_rate: 31},
			{name: '<div><a class="q4" href="">审判护手</a></div>', drop_rate: 29},
			{name: '<div><a class="q4" href="">玛法里奥的祝福</a></div>', drop_rate: 18},
			{name: '<div><a class="q4" href="">龙息手持火炮</a></div>', drop_rate: 16},
			{name: '<div><a class="q4" href="">愤怒护手</a></div>', drop_rate: 16},
			{name: '<div><a class="q4" href="">灵风手套</a></div>', drop_rate: 15},
			{name: '<div><a class="q4" href="">卓越护手</a></div>', drop_rate: 15},
			{name: '<div><a class="q4" href="">巨龙追猎者护手</a></div>', drop_rate: 14},
			{name: '<div><a class="q4" href="">复仇手套</a></div>', drop_rate: 13},
			{name: '<div><a class="q4" href="">恢复宝石</a></div>', drop_rate: 13},
			{name: '<div><a class="q4" href="">紧绷的龙皮腰带</a></div>', drop_rate: 13},
            {name: '<div><a class="q4" href="">黑石之戒</a></div>', drop_rate: 12},
			{name: '<div><a class="q4" href="">怒风护手</a></div>', drop_rate: 12},
			{name: '<div><a class="q4" href="">血牙手套</a></div>', drop_rate: 10},
			{name: '<div><a class="q4" href="">龙爪肩铠</a></div>', drop_rate: 9},
			{name: '<div><a class="q4" href="">龙爪巨斧</a></div>', drop_rate: 9},
			{name: '<div><a class="q4" href="">暗影之翼</a></div>', drop_rate: 5}
	]},
	{
		boss:"弗莱格尔", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">纯净思想斗篷</a></div>'},
			{name: '<div><a class="q4" href="">源力之环</a></div>'},
			{name: '<div><a class="q4" href="">灰烬护腿</a></div>'},
			{name: '<div><a class="q4" href="">斯泰林的甲虫壳</a></div>'},
			{name: '<div><a class="q4" href="">巨龙之触</a></div>'},
			{name: '<div><a class="q4" href="">悲哀使者</a></div>'},
			{name: '<div><a class="q4" href="">紧绷的龙皮腰带</a></div>'},
			{name: '<div><a class="q4" href="">卓越护手</a></div>'},
			{name: '<div><a class="q4" href="">愤怒护手</a></div>'},
            {name: '<div><a class="q4" href="">灵风手套</a></div>'},
			{name: '<div><a class="q4" href="">血牙手套</a></div>'},
			{name: '<div><a class="q4" href="">审判护手/无尽风暴护手</a></div>'},
			{name: '<div><a class="q4" href="">怒风护手</a></div>'},
			{name: '<div><a class="q4" href="">黑石之戒</a></div>'},
			{name: '<div><a class="q4" href="">复仇手套</a></div>'},
            {name: '<div><a class="q4" href="">巨龙追猎者护手</a></div>'},
			{name: '<div><a class="q4" href="">恢复宝石</a></div>'},
			{name: '<div><a class="q4" href="">龙爪肩铠</a></div>'},
			{name: '<div><a class="q4" href="">龙爪巨斧</a></div>'},
			{name: '<div><a class="q4" href="">暗影之翼</a></div>'}
	]},
	{
		boss:"克洛玛古斯", 
		num_drops: 3,
		items:[
			{name: '<div><a class="q4" href="">灵风衬肩</a></div>'},
			{name: '<div><a class="q4" href="">卓越肩铠</a></div>'},
			{name: '<div><a class="q4" href="">巨龙追猎者肩甲</a></div>'},
			{name: '<div><a class="q4" href="">愤怒肩铠</a></div>'},
			{name: '<div><a class="q4" href="">紧绷的龙皮护肩</a></div>'},
			{name: '<div><a class="q4" href="">血牙肩甲</a></div>'},
			{name: '<div><a class="q4" href="">复仇肩铠</a></div>'},
			{name: '<div><a class="q4" href="">安格莉丝塔之握</a></div>'},
			{name: '<div><a class="q4" href="">怒风肩甲</a></div>'},
			{name: '<div><a class="q4" href="">闪光之鞋</a></div>'},
			{name: '<div><a class="q4" href="">多彩长靴</a></div>'},
			{name: '<div><a class="q4" href="">紧绷的龙皮手套</a></div>'},
            {name: '<div><a class="q4" href="">强能护腿</a></div>'},
			{name: '<div><a class="q4" href="">源质丝线披风</a></div>'},
			{name: '<div><a class="q4" href="">堕落十字军腰带</a></div>'},
			{name: '<div><a class="q4" href="">审判肩铠/无尽风暴肩饰</a></div>'},
			{name: '<div><a class="q4" href="">克洛玛古斯之爪</a></div>'},
			{name: '<div><a class="q4" href="">首领锁链腰带</a></div>'},
			{name: '<div><a class="q4" href="">埃瑟利苏尔，惩戒之弩</a></div>'},
			{name: '<div><a class="q4" href="">多彩之剑</a></div>'},
			{name: '<div><a class="q4" href="">源质壁垒</a></div>'}
	]},
	{
		boss:"奈法利安", 
		num_drops: 4,
		items:[
			{name: '<div><a class="q4" href="">灵风长袍</a></div>'},
			{name: '<div><a class="q4" href="">龙王披风</a></div>'},
			{name: '<div><a class="q4" href="">巨龙追猎者胸甲</a></div>'},
			{name: '<div><a class="q4" href="">愤怒胸甲</a></div>'},
			{name: '<div><a class="q4" href="">塞拉赞恩之链</a></div>'},
			{name: '<div><a class="q4" href="">血牙胸甲</a></div>'},
			{name: '<div><a class="q4" href="">卓越法袍</a></div>'},
			{name: '<div><a class="q4" href="">阿基迪罗斯的清算之戒</a></div>'},
			{name: '<div><a class="q4" href="">怒风胸甲</a></div>'},
			{name: '<div><a class="q4" href="">普瑞斯托的阴谋饰物</a></div>'},
			{name: '<div><a class="q4" href="">复仇法袍</a></div>'},
			{name: '<div><a class="q4" href="">奈萨里奥之泪</a></div>'},
			{name: '<div><a class="q4" href="">暗影烈焰长靴</a></div>'},
			{name: '<div><a class="q4" href="">纯源质指环</a></div>'},
			{name: '<div><a class="q4" href="">密苏达尔，夺魂者的头饰</a></div>'},
			{name: '<div><a class="q4" href="">审判胸甲/无尽风暴胸甲</a></div>'},
			{name: '<div><a class="q4" href="">暗影烈焰法杖</a></div>'},
			{name: '<div><a class="q4" href="">阿什坎迪，兄弟会之剑</a></div>'},
            {name: '<div><a class="q4" href="">洛卡米尔·伊洛曼希斯</a></div>'},
			{name: '<div><a class="q4" href="">克鲁索洛克恩，混乱之刃</a></div>'}
	]}
]